### PR TITLE
WIP: Add/pytests

### PR DESCRIPTION
**Pull request by kaczmarj**
WIP adding python tests.

### CODE REVIEW

**Comment by kaczmarj** [comment]
The test `test/pytest_tests/test_help_messages.py` fails with the following output:

```
PROGRAMS NOT FOUND:
    testGL
PROGRAMS THAT FAILED:
    3dSurf2Vol (return code 255)
    3dVol2Surf (return code 255)
    3dmaxima (return code 1)
    @Install_D99_macaque (Unmatched '"'.)
    @Install_NIH_Marmoset (Unmatched '"'.)
    @auto_align (return code 1)
    @djunct_4d_slices_to_3d_vol (SHOW_HELP: label not found.)
    @djunct_vol_3slice_select (return code 1)
    @xyz_to_ijk (return code 1)
    Dimon (return code 1)
    Dimon1 (return code 1)
    FD2 ( )
    Ifile (return code 1)
    MakeColorMap (return code 1)
    RetroTS.py (ImportError: No module named pylab)
    ScaleToMap (return code 1)
    SurfMeasures (return code 255)
    afni_run_R (return code 1)
    balloon (	behavioural variable such as reaction time.))
    cjpeg (  -scans file    Create multi-scan JPEG per script file)
    column_cat (return code 1)
    djpeg (  -verbose  or  -debug   Emit debug output)
    fat_lat_csv.py (ImportError: No module named rpy2.robjects)
    fat_mat_sel.py (ImportError: No module named matplotlib.pyplot)
    fat_mvm_gridconv.py (return code 2)
    fat_mvm_prep.py (return code 2)
    fat_mvm_review.py (return code 2)
    fat_mvm_scripter.py (return code 2)
    fat_proc_grad_plot (ImportError: No module named mpl_toolkits.basemap)
    fat_roi_row.py (return code 2)
    get_afni_model_PRF (** usage: get_afni_model_PRF A x y sigma)
    imcat (** ERROR: Too few options)
    inspec (return code 1)
    mpeg_encode (	-mv_histogram:  show histograms of motion vectors)
    myget (Can't open URL -help)
    qdelaunay (  run-id 40915041  delaunay  Qbbound-last)
    qhull (  run-id 40915041)
    quickspec (return code 1)
    rbox (QH7071 rbox error: missing space between flags at elp.)
```

In several cases of non-zero exit codes, running `program -help` returns non-zero and that counts as an error. The source code of those programs can be modified to return 0 when asking for `-help`.

`testGL` is listed by `make prog_list` but is not present.

**Comment by kaczmarj** [comment]
The commit ec9227f is an initial attempt to return 0 when using `program -help`. Rick says not to replace `return` with `exit(0`) -- instead to modify the logic of the program to return 0 at the end if given `-help`.

also afni/afni:master should be merged into this branch, because some programs have been changed recently to return 0 with `-help`.

**Comment by Shotgunosine** [comment]
do you need me to merge master into my pr, or do you want do do it on yours?

**Comment by kaczmarj** [comment]
@Shotgunosine - can you merge master into your branch?

**Comment by kaczmarj** [comment]
I recommend viewing the diff with whitespace changes off.

**Pull request merged**
